# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: head.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'head.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhead.proto\x12\rpbTableHeader\"O\n\tTransform\x12\x0e\n\x06offset\x18\x01 \x01(\x05\x12\x0e\n\x06multip\x18\x02 \x01(\x05\x12\x10\n\x08\x64\x65\x63imals\x18\x03 \x01(\x05\x12\x10\n\x08sequence\x18\x04 \x01(\x08\"K\n\x05Stats\x12\r\n\x05start\x18\x01 \x01(\x01\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x01\x12\x0b\n\x03min\x18\x03 \x01(\x01\x12\x0b\n\x03max\x18\x04 \x01(\x01\x12\x0c\n\x04mean\x18\x05 \x01(\x01\"u\n\x05\x46ield\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12+\n\ttransform\x18\x06 \x01(\x0b\x32\x18.pbTableHeader.Transform\x12#\n\x05stats\x18\x07 \x01(\x0b\x32\x14.pbTableHeader.Stats\"U\n\x04Meta\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\t\x12\x0c\n\x04link\x18\x03 \x01(\t\x12\x0f\n\x07\x63omment\x18\x04 \x01(\t\x12\x11\n\trow_count\x18\x05 \x01(\x05\"T\n\ttableHead\x12$\n\x06header\x18\x01 \x03(\x0b\x32\x14.pbTableHeader.Field\x12!\n\x04meta\x18\x02 \x01(\x0b\x32\x13.pbTableHeader.Meta\"\x05\n\x03Row\"(\n\x04\x44\x61ta\x12 \n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x12.pbTableHeader.Rowb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'head_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSFORM']._serialized_start=29
  _globals['_TRANSFORM']._serialized_end=108
  _globals['_STATS']._serialized_start=110
  _globals['_STATS']._serialized_end=185
  _globals['_FIELD']._serialized_start=187
  _globals['_FIELD']._serialized_end=304
  _globals['_META']._serialized_start=306
  _globals['_META']._serialized_end=391
  _globals['_TABLEHEAD']._serialized_start=393
  _globals['_TABLEHEAD']._serialized_end=477
  _globals['_ROW']._serialized_start=479
  _globals['_ROW']._serialized_end=484
  _globals['_DATA']._serialized_start=486
  _globals['_DATA']._serialized_end=526
# @@protoc_insertion_point(module_scope)
